//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolV01.Client.Resources.Pages.Menus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolV01.Client.Resources.Pages.Menus.Menus", typeof(Menus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Menu.
        /// </summary>
        public static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Menu Category.
        /// </summary>
        public static string AddMenuCategory {
            get {
                return ResourceManager.GetString("AddMenuCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Translation.
        /// </summary>
        public static string AddTranslation {
            get {
                return ResourceManager.GetString("AddTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Description.
        /// </summary>
        public static string Arabic_Description {
            get {
                return ResourceManager.GetString("Arabic Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string Arabic_Name {
            get {
                return ResourceManager.GetString("Arabic Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description.
        /// </summary>
        public static string English_Description {
            get {
                return ResourceManager.GetString("English Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string English_Name {
            get {
                return ResourceManager.GetString("English Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HtmlText.
        /// </summary>
        public static string HtmlText {
            get {
                return ResourceManager.GetString("HtmlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langugae code.
        /// </summary>
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Order.
        /// </summary>
        public static string LevelOrder {
            get {
                return ResourceManager.GetString("LevelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus Categories.
        /// </summary>
        public static string MenuCategoriesDescription {
            get {
                return ResourceManager.GetString("MenuCategoriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Available Menus.
        /// </summary>
        public static string MenusDescription {
            get {
                return ResourceManager.GetString("MenusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Translation data For :.
        /// </summary>
        public static string NoTranslationData {
            get {
                return ResourceManager.GetString("NoTranslationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Url.
        /// </summary>
        public static string PageUrl {
            get {
                return ResourceManager.GetString("PageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Menu.
        /// </summary>
        public static string ParentName {
            get {
                return ResourceManager.GetString("ParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string selectCategory {
            get {
                return ResourceManager.GetString("selectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Menus.
        /// </summary>
        public static string SubMenus {
            get {
                return ResourceManager.GetString("SubMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Details For :.
        /// </summary>
        public static string TranslationDetails {
            get {
                return ResourceManager.GetString("TranslationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Menu.
        /// </summary>
        public static string UpdateMenu {
            get {
                return ResourceManager.GetString("UpdateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Menu Category.
        /// </summary>
        public static string UpdateMenuCategory {
            get {
                return ResourceManager.GetString("UpdateMenuCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Translation.
        /// </summary>
        public static string UpdateTransalation {
            get {
                return ResourceManager.GetString("UpdateTransalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string ViewMenus {
            get {
                return ResourceManager.GetString("ViewMenus", resourceCulture);
            }
        }
    }
}
